backend:
  name: git-gateway
  branch: main

media_folder: /
public_folder: /

publish_mode: simple

collections:
  - name: products
    label: Mahsulotlar
    label_singular: Mahsulot
    files:
      - name: products
        label: Mahsulotlar ro'yxati
        file: products.json
        format: json
        fields:
          - name: products
            label: Mahsulotlar
            widget: list
            fields:
              - name: id
                label: ID
                widget: string
              - name: name
                label: Nomi
                widget: string
              - name: category
                label: Kategoriya
                widget: select
                options:
                  - Telefonlar
                  - Noutbuklar
                  - Kompyuterlar
                  - Planshetlar
                  - Televizorlar
                  - Audio
                  - Uy texnikasi
                  - Aksessuarlar
              - name: price
                label: Narxi (so'm)
                widget: number
                value_type: int
              - name: old_price
                label: Eski narxi (chegirma bo'lsa)
                widget: number
                value_type: int
                required: false
              - name: flag
                label: Belgi
                widget: select
                required: false
                options:
                  - new
                  - sale
              - name: section
                label: Bo'lim
                widget: select
                options:
                  - best
                  - new
              - name: image
                label: Rasm
                widget: image
                required: false
